server {
    listen 80;
    
    # Carpeta donde Vite guarda tu web compilada
    root /usr/share/nginx/html;
    index index.html;

    # La magia para React: Si la ruta no existe, envíalo al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}